import React, {useEffect, useState} from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import axios from 'axios'

axios.defaults.baseURL = process.env.NODE_ENV === 'production' ? process.env.REACT_APP_API_PROD_URL : process.env.REACT_APP_API_LOCAL_URL

export default function Home() {
  const [leads, setLeads] = useState([])
  const [transactions, setTransactions] = useState([])
  useEffect(() => {
    const url = 'https://618f275750e24d0017ce1630.mockapi.io/api/v1/leads'
    axios.get(url).then(({data}) => {
      setLeads(data)
    })
  }, [])
  useEffect(() => {
    const url = 'https://618f275750e24d0017ce1630.mockapi.io/api/v1/transactions'
    axios.get(url).then(({data}) => {
      setTransactions(data)
    })
  }, [])
  return (
    <div className={styles.container}>
      <Head>
        <title>Hello</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Helo this is a test
        </h1>

        <p className={styles.description}>
          mock users
        </p>
        <table>
          <thead>
            <tr>
              <td>first name</td>
              <td>last name</td>
              <td>address</td>
              <td>country name</td>
            </tr>
          </thead>
          <tbody>
            {leads.map(lead => {
              return (
                <tr key={lead.id}>
                  <td>{lead.first_name}</td>
                  <td>{lead.last_name}</td>
                  <td>{lead.contact}</td>
                  <td>{lead.address}</td>
                  <td>{lead.country}</td>
                </tr>
              )
            })}
          </tbody>
            
        </table>
        <p className={styles.description}>
          mock transactions
        </p>
        <table>
          <thead>
            <tr>
              <td>amount</td>
              <td>account name</td>
              <td>account number</td>
              <td>transaction type</td>
            </tr>
          </thead>
          <tbody>
            {transactions.map(transaction => {
              return (
                <tr key={transaction.id}>
                  <td>{transaction.amount}</td>
                  <td>{transaction.account_name}</td>
                  <td>{transaction.account_number}</td>
                  <td>{transaction.transaction_type}</td>
                </tr>
              )
            })}
          </tbody>
            
        </table>
        
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
